### ISSUE TITLE
Currently project doesn't work well on windows.

### ISSUE THREAD

**Issue by HSCorp99906** [HSCorp666/HSCtoolkit#1]
Windows support is currently a little wonky. But do not worry, we will get it fixed very soon!

**Comment by NotBlackrus** [comment]
Currently working on it

**Comment by HSCorp99906** [comment]
Windows support has been added. If any more problems come re-open the issue, I am closing this for now.

**Comment by HSCorp99906** [comment]
*sigh* Windows support broke.

**Comment by HSCorp99906** [comment]
Just use a Linux virtual machine.

https://ubuntu.com/download/desktop/thank-you?version=20.04.2.0&architecture=amd64

https://www.virtualbox.org/
